const trim = (input: string) => input.trim().slice(0, 9) || "local"

export function release(input: { target: string; version: string; rev: string }) {
  const id = `opencode-web-${input.target}-${input.version}-${trim(input.rev)}`
  return {
    name: id,
    root: id,
    archive: `${id}.tar.gz`,
    stage: {
      app: "app",
      env: "env/server.env.example",
      health: "bin/check-health.sh",
      readme: "README.md",
      server: "server/bin/opencode",
      start: "bin/start-server.sh",
    },
    env: [
      "# Copy this file to env/server.env before starting the backend.",
      'OPENCODE_SERVER_PASSWORD=change-me',
      "OPENCODE_SERVER_USERNAME=opencode",
      "OPENCODE_SERVER_HOSTNAME=127.0.0.1",
      "OPENCODE_SERVER_PORT=4096",
      "OPENCODE_SERVER_CORS=https://your-domain.example.com",
    ].join("\n"),
    start: [
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      'root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)',
      'envfile=${1:-"$root/env/server.env"}',
      'if [ ! -f "$envfile" ]; then',
      '  echo "missing env file: $envfile" >&2',
      "  exit 1",
      "fi",
      'set -a',
      '. "$envfile"',
      'set +a',
      'exec "$root/server/bin/opencode" serve \\',
      '  --hostname "$OPENCODE_SERVER_HOSTNAME" \\',
      '  --port "$OPENCODE_SERVER_PORT" \\',
      '  --cors "$OPENCODE_SERVER_CORS"',
    ].join("\n"),
    health: [
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      'port=${OPENCODE_SERVER_PORT:-4096}',
      'url=${1:-"http://127.0.0.1:${OPENCODE_SERVER_PORT:-4096}/global/health"}',
      'curl -fsS "$url"',
      'echo ""',
      'echo "health ok on 127.0.0.1:${OPENCODE_SERVER_PORT:-4096}"',
      'test -n "$port"',
    ].join("\n"),
    readme: [
      "# OpenCode Web Release",
      "",
      "1. Copy `env/server.env.example` to `env/server.env` and update values.",
      "2. Start the backend with `./bin/start-server.sh`.",
      "3. Verify the backend with `./bin/check-health.sh`.",
      "4. Serve the `app/` directory from your web server on the same origin as the backend API.",
      "",
      "Extract command:",
      "",
      "```bash",
      "tar -xzf opencode-web-<version>-<rev>.tar.gz",
      "```",
      "",
      "Runtime files:",
      "",
      "- `env/server.env`",
      "- `bin/start-server.sh`",
      "- `bin/check-health.sh`",
    ].join("\n"),
  }
}
